# Spring Boot application configuration
spring:
  application:
    name: demo
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  data:
    redis:
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}
      port: ${REDIS_PORT}
  lifecycle:
    timeout-per-shutdown-phase: 30s
  threads:
    virtual:
      enabled: true
server:
  shutdown: graceful

# Forex Gateway configuration
forex:
  # Comma-separated list of currency pairs to subscribe to.
  # Example: EURUSD,GBPUSD,USDJPY
  instruments: ${FOREX_INSTRUMENTS}

  # Comma-separated list of candle periods for the subscribed instruments.
  # Valid values are from the Dukascopy Period enum, e.g., ONE_MIN, FIVE_MINS, FIFTEEN_MINS, ONE_HOUR, DAILY
  periods: ${FOREX_PERIODS}

gateway:
  kline:
    storage-limit: ${GATEWAY_KLINE_STORAGE_LIMIT}
  heartbeat:
    fixed-rate: ${GATEWAY_HEARTBEAT_INTERVAL}

# JForex Connection Settings
jforex.url: ${JFOREX_URL}
jforex.username: ${JFOREX_USERNAME}
jforex.password: ${JFOREX_PASSWORD}